### ISSUE TITLE
Connex Vendor does not work properly

### ISSUE THREAD

**Issue by Talented-Developer** [vechain/connex#113]
I am now using connex to sign transfer with node.js, but it fails with following error.

```
(node:6432) UnhandledPromiseRejectionWarning: TypeError: connex.vendor.sign(...).signer(...).gas(...).link(...).comment(...).then is not a function
    at VechainLogic.<anonymous> (D:\Worksite\dvst\dvst-web3\build\chains\Vechain.js:203:42)
    at step (D:\Worksite\dvst\dvst-web3\build\chains\Vechain.js:63:23)
    at Object.next (D:\Worksite\dvst\dvst-web3\build\chains\Vechain.js:44:53)
    at fulfilled (D:\Worksite\dvst\dvst-web3\build\chains\Vechain.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I just followed this instruction: #https://docs.vechain.org/connex/api.html#transaction-signing-service
Hope to know how to proceed in this case.

**Comment by libotony** [comment]
The example was wrong in the doc, it should be `connex.vendor.sign(...).signer(...).gas(...).link(...).comment(...).request().then`, I will update the doc ASAP.

**Comment by Talented-Developer** [comment]
Thank you very much

**Comment by Talented-Developer** [comment]
And the mechanism to sign transaction is not so clear in the doc.
For example, how to customize transferABI aand transferMethod in the doc
const transferABI = {"constant":false,"inputs":[{"name":"_to","type":"address"},
```
{"name":"_amount","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"}
const transferMethod = connex.thor.account('0x0000000000000000000000000000456E65726779').method(transferABI)
// Connex author's address and amount in wei
const energyClause = transferMethod.asClause('0xd3ae78222beadb038203be21ed5ce7c9b1bff602', '1000000000000000000000')

connex.vendor.sign('tx', [
    {
        to: '0xd3ae78222beadb038203be21ed5ce7c9b1bff602',
        value: '100000000000000000000',
        data: '0x',
        comment: 'Transfer 100 VET'
    },
    {
        comment: 'Transfer 1000 VeThor',
        ...energyClause
    }
])
```

Then how is the private key used for signing?
Isn't it neccessary?

**Comment by libotony** [comment]
ABI is given by the solidity compiler.

**Comment by libotony** [comment]
Private key management is done by `simple wallet` from [connex-driver](https://github.com/vechain/connex/tree/master/packages/driver)

**Comment by Talented-Developer** [comment]
got it
But the document for creating and sending transaction is not changed yet.
When will it be ready for use?

**Comment by libotony** [comment]
Doc is updated, for your case add `.request()` before `.then`.

**Comment by Talented-Developer** [comment]
ok, I will try it.
Would you please tell me what is the address in this part?
`const transferMethod = connex.thor.account('0x0000000000000000000000000000456E65726779').method(transferABI)`

**Comment by libotony** [comment]
https://docs.vechain.org/connex/api.html#account-visitor, documented here the address in `account(address)` is the contract's address, here I used `VTHO` contract for example.

**Comment by Talented-Developer** [comment]
So you mean if I want to transfer VET, I have to use another address?

**Comment by libotony** [comment]
No, transfer VET just needs add a clause `{to: <address>, value: <value>}`

**Comment by libotony** [comment]
``` typescript
connex.vendor.sign('tx', [
    {
        to: '0xd3ae78222beadb038203be21ed5ce7c9b1bff602',
        value: '100000000000000000000',
        data: '0x',
        comment: 'Transfer 100 VET'
    }
])
```

**Comment by Talented-Developer** [comment]
Thanks
Then How can I export private key from Sync2 wallet?
I can not find it anywhere

**Comment by libotony** [comment]
Sync2 does not support exporting the private key, but you can do it with [thor-devkit](https://github.com/vechain/thor-devkit.js) with your mnemonic words.

**Comment by Talented-Developer** [comment]
Thank you very much.
