### ISSUE TITLE
How to fetch events in the order that they were emitted from a specific Smart Contract?

### ISSUE THREAD

**Issue by LinSays** [vechain/connex#116]
Hi.
I want to fetch events emitted from the SC in VeChain using connex.
But I have to use loop the abis of the SC to fetch all the events emitted from the SC since the events instance has parameter for only one abi.
So this will result like this: [eventsFromAbi1, eventsFromAbi2 .....]
However, even this way can't solve my problem. I have to get the events in the order that they were emitted.
My solution is to sort the events by the order of blocknumber. But is there any smart way to handle this issue.
Best regards.

**Comment by libotony** [comment]
Use the general filter https://docs.vechain.org/connex/api.html#filter
