### ISSUE TITLE
index.d.ts' is not a module

### ISSUE THREAD

**Issue by malikov917** [vechain/connex#46]
hi, I have angular 5 project and currently face with a problem:
### in my app.component.ts
**import {Connex} from '@vechain/connex';**
**_node_modules/@vechain/connex/index.d.ts' is not a module_**

tsconfig.app.json is:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": ["@vechain/connex"]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": ["@vechain/connex"], // tried this too ->["node_modules/@vechain/connex"]
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "exclude": [
    "dist"
  ],
  "include": [
    "**/*.ts"
  ]
}
```

in addition:

`ERROR in node_modules/@vechain/connex/index.d.ts(438,19): error TS1005: ';' expected.
node_modules/@vechain/connex/index.d.ts(439,19): error TS1005: ';' expected.
node_modules/@vechain/connex/index.d.ts(447,19): error TS1005: '>' expected.
node_modules/@vechain/connex/index.d.ts(448,19): error TS1005: ';' expected.
node_modules/@vechain/connex/index.d.ts(449,9): error TS1109: Expression expected.
node_modules/@vechain/connex/index.d.ts(540,15): error TS1005: ';' expected.
node_modules/@vechain/connex/index.d.ts(541,15): error TS1005: ';' expected.
`

Angular CLI: 1.7.4
Node: 8.11.2
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack-raphael: 2.1.4
webpack: 3.11.0

**Comment by qianbin** [comment]
@malikov917 no need to import. 'types' settings in tsconfig is all right.

**Comment by malikov917** [comment]
@qianbin then how to use connex inside a project?
even after 
`declare const connex;`
I'm getting:
_ERROR ReferenceError: connex is not defined_

**Comment by qianbin** [comment]
I'm not familiar with angular, while you can check the tips at https://github.com/vechain/connex#typescript-complier-does-not-find-connex

**Comment by malikov917** [comment]
@qianbin I've tried this tips without result

**Comment by qianbin** [comment]
Have you tried to remove `typeRoots` in tsconfig.json?

**Comment by malikov917** [comment]
@qianbin hm I need it for
` "typeRoots": [ "node_modules/@types" ]`

**Comment by qianbin** [comment]
try upgrade typescript to latest release

**Comment by malikov917** [comment]
@qianbin Ok, update up to "typescript": "3.4.5" (latest), still getting same issue

> File '.../node_modules/@vechain/connex/index.d.ts' is not a module.

**Comment by qianbin** [comment]
@malikov917 Remove the line `import {Connex} from '@vechain/connex';`

**Comment by malikov917** [comment]
@qianbin but how can I use 'connex' inside a project?

**Comment by malikov917** [comment]
@qianbin thank you for your support, actually I've figured out how to make it work. In 10 minutes I'll leave a short review and "close and comment" 💯

**Comment by qianbin** [comment]
@malikov917 :-)  wondering how

**Comment by malikov917** [comment]
@qianbin I appreciate your support, well the solution was:
0. Work via Sync App

1. NOT to import it via:
`import {Connex} from '@vechain/connex';`

2. Just declare it like:
`declare const window;
declare const connex;`

Rest of things are described in dev tips in instruction on Connex

**Comment by malikov917** [comment]
hm I just thought one more time on that and decided that usage of Typescript is impossible still. I'm supposing that this issue still has a sense
