### ISSUE TITLE
Vechain Connex Integration

### ISSUE THREAD

**Issue by osiz-blockchainapp** [vechain/connex#62]
I am facing issue at Connex Library Integration.

_sample code_

const acc = connex.thor.account('0x7567d83b7b8d80addcb281a71d54fc7b3364ffed')
acc.get().then(accInfo=>{
    console.log(accInfo)
**I didn't get any response here**
})

Anyone know, how to solve this kindly help me.

**Comment by qianbin** [comment]
@osiz-blockchainapp which wallet is being used? I just tried in sync, and it works: 
<img width="542" alt="截屏2020-02-28下午4 16 51" src="https://user-images.githubusercontent.com/494645/75522791-c013fc80-5a45-11ea-8a6e-37daac8d60d7.png">

**Comment by osiz-blockchainapp** [comment]
![1](https://user-images.githubusercontent.com/48212011/75671798-690c6280-5ca5-11ea-8da9-b3530baba719.png).

In that above picture, the connex library is undefined.

-------------
![2](https://user-images.githubusercontent.com/48212011/75671999-cef8ea00-5ca5-11ea-8267-57c8a41a4637.png)

In this picture, the connex library is working.

kindly let me know, the connex library process because I have a comet wallet in browser.

-------------
I need the connex library package as like CDN or any other installation package setup in my local. If Anyone knows, kindly help me

**Comment by qianbin** [comment]
> I need the connex library package as like CDN or any other installation package setup in my local. If Anyone knows, kindly help me

these repos might help:

https://github.com/vechain/connex-framework
https://github.com/vechain/connex.driver-nodejs

also a REPL playground:

https://github.com/vechain/connex-repl

**Comment by osiz-blockchainapp** [comment]
It's resolved. Thanks.
