### ISSUE TITLE
Vechain Network Connex

### ISSUE THREAD

**Issue by desingraja** [vechain/connex#66]
Hi Vechain Team,
                          **Vechain connex Implementation**
                     I was developed a Application in Vechain Network based on the connex library in server side. Now I need that connex library in browser side, like cdn packages to load it in the browser. kindly If any packages available means, help me to integrate.

**Comment by qianbin** [comment]
usually, if you are building a dapp running in browser, no library is needed except for the pkg @vechain/connex which only provides typings. however, if do require connex embedded in dapp, libraries working at the server side also work in browser, only thing to do is building the libraries into umd using tools like Webpack.
