### ISSUE TITLE
Connex NodeJs driver

### ISSUE THREAD

**Issue by desingraja** [vechain/connex#68]
Hi connex team,
 
              I was implemented the connex framework by the connex.driver-nodejs environment. From these I used a connex object. That connex object have few keys only i.e { connex version, connex.thor ('genesis', 'status') },
but huge keys things were missing in connex.thor object such as expected to have keys
  'ticker', 'account', 'block', 'transaction', 'filter', and 'explain'.
Those are all missing keys. kindly help me, If anyone knows.

**Comment by qianbin** [comment]
How about the object directly returned by `new Framework(...)`? Seems the object was JSON encoded/decoded.

**Comment by desingraja** [comment]
kindly explain it clearly, I used this Driver.
code :-  // NodeJs Driver

import { Framework } from '@vechain/connex-framework'
import { Driver, SimpleNet, SimpleWallet, options } from '@vechain/connex.driver-nodejs'
const wallet = new SimpleWallet()
const driver = await Driver.connect(new SimpleNet('http://localhost:8669/'), wallet)
const connex = new Framework(driver)
// here I get the connex object.

what was the problem in these. kindly explain clearly to me.

**Comment by qianbin** [comment]
the Connex object got here should be fully functional. just try
```
connex.thor.block('best').then(b => console.log(b))
```

**Comment by desingraja** [comment]
yeah it is working, connex.thor.account and connex.thor.block which are all working fine. but I didn't get any object in the connex. which displays only the genesis and status at here.
const connex = new Framework(driver)
// here I get the connex object.

**Comment by qianbin** [comment]
What does 'displays' mean here?

**Comment by desingraja** [comment]
It returns the object { connex version, connex.thor ('genesis', 'status') }
I need  'ticker', 'account', 'block', 'transaction', 'filter', and 'explain' these things in the connex object.

**Comment by qianbin** [comment]
They're there, a you said you can access 'connex.thor.account and connex.thor.block which are all working fine'

**Comment by desingraja** [comment]
yeah the functionality is working but I didn't receive that key in connex framework object.
It displays the only two keys in the object code [ "const connex = new Framework(driver)"] // here I get the connex object.I attached the image below. 

I need the rest off keys 'ticker', 'account', 'block', 'transaction', 'filter', and 'explain' in the connex object
![connex obj](https://user-images.githubusercontent.com/31981073/79826691-06d50180-83ba-11ea-94d2-2411d37dddb8.png)

**Comment by qianbin** [comment]
the object must have been transformed with JSON.stringify and JSON.parse. then, functions will be all ignored.

**Comment by desingraja** [comment]
If it possible to fetch the remaining keys 'ticker', 'account', 'block', 'transaction', 'filter', and 'explain' in that connex object. Any possible ways to fetch it

**Comment by qianbin** [comment]
No. You can't remotely fetch a function.

**Comment by desingraja** [comment]
Then how I fetch it from connex Framework.Kindly help me

**Comment by qianbin** [comment]
how about placing the Framework creation code to where using it?

**Comment by desingraja** [comment]
To use in the server side object, 
Framework creation code is 
import { Framework } from '@vechain/connex-framework'
import { Driver, SimpleNet, SimpleWallet, options } from '@vechain/connex.driver-nodejs'
const wallet = new SimpleWallet()
const driver = await Driver.connect(new SimpleNet('http://localhost:8669/'), wallet)
const connex = new Framework(driver)
// connex ---  here I get the connex object.

**Comment by qianbin** [comment]
I mean put the code at the place where using connex, e.g. client/browser side.

**Comment by desingraja** [comment]
I need the those objects keys in server side.

**Comment by desingraja** [comment]
I used the connex Driver package in NodeJs . so now how I used that in client/browser side. Kindly help me to integrate.

**Comment by desingraja** [comment]
I find the way, thanks !
