### ISSUE TITLE
[ABIEncoderV2] Tuple input not working

### ISSUE THREAD

**Issue by tv-truong** [vechain/connex#91]
I tested a contract like the image below (testnet)
then call the [set] method with connex, and they always return "reverted: true"
can you show me how to call the above method?

![image](https://user-images.githubusercontent.com/54877733/126051187-aee6ce29-4d96-4742-8ded-cd8d9a70f95d.png)
![image](https://user-images.githubusercontent.com/54877733/126051250-b3b004e3-7ec8-4414-9906-9432b48bee80.png)

**Comment by qianbin** [comment]
how did you pass the value of the _inputs argument? it would be something like [{a: 1, b: 1}].

**Comment by tv-truong** [comment]
@qianbin I tried many ways but it doesn't work
[{a: 1, b: 1}]: alert -> Unexpected token a in JSON at position 2

[{"a": "1", "b": "1"}]: result -> "reverted": true,

**Comment by libotony** [comment]
@tv-truong It's a bug in connex v1 implementation. I'll let you know once it's fixed. The right input should be:

+ Inspector, `JSON.stringify([{a:1, b:1}])`
+ connex, `yourMethod.call([{a:1, b:1}])`

**Comment by tv-truong** [comment]
@qianbin Thank you, I'm waiting for good news from you!

**Comment by libotony** [comment]
Fixed in [thor-sync.electron v1.3.1](https://github.com/vechain/thor-sync.electron/releases/tag/v1.3.1)
