### ISSUE TITLE
Ticker only returns gasLimit

### ISSUE THREAD

**Issue by KennethAshley** [vechain/connex#92]
When calling `await connex.thor.ticker().next()` it returns `{gasLimit: 20000000}`. 

Here is an example:
![image](https://user-images.githubusercontent.com/1138619/126434754-e1cd9318-e70d-4961-8286-dc9d56e629de.png)

Here is a link to the sandbox https://codesandbox.io/s/nostalgic-sunset-4cvem?file=/src/App.js

**Comment by libotony** [comment]
After some time digging, we found out that comet extension will cause this. So either disable comet extension or enable the noV1Compat option.

**Comment by KennethAshley** [comment]
@libotony thanks for the update Tony! Stay safe!
